import express from "express";
import { isloggedin, signupStudent, StudentLogin } from "../controllers/auth.controller.js";
import { StaffLogin } from "../controllers/auth.controller.js";
import { logout } from "../controllers/auth.controller.js";
const router = express.Router();
router.post("/signup", signupStudent);
router.post("/student/login", StudentLogin);
router.post("/logout", logout);
router.post("/admin/login", StaffLogin);
router.get("/isloggedin", isloggedin);
export default router;
